<a href="https://colab.research.google.com/github/pypankj30/Rebounce-Applied-AI-and-Analytics-Codes/blob/main/Python_301.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment MP3- Clean Analyse Summarise**

**Part 1 - Load and understand the data**

Importing pandas and numpy

In [ ]:
import pandas as pd
import numpy as np

Loading data directly from web so that nothing loses when runtime restarts

In [ ]:
url = "https://huggingface.co/datasets/aarav912/online-retail/resolve/main/online_retail.csv"
df = pd.read_csv(url)

Displaying first few rows

In [ ]:
df.duplicated().sum()

np.int64(5268)

Checking the shape - how many rows and columns?

In [ ]:
print(df.shape)
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

(541909, 8)
Number of rows: 541909
Number of columns: 8

Listing column names

In [ ]:
print(df.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

Checking data types of each column

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

Counting missing values in every column

In [ ]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Counting the duplicated rows

In [ ]:
df.duplicated().sum()

np.int64(5268)

Description and CustomerID have null values , so they need cleaning

**Part 2- Clean the data**

In [45]:
#copy of clean original data
clean_df = df.copy()
print(clean_df.shape)

(541909, 8)

Keeping missing customerID becuase dropping them could impact overall data analysis as they are large in number

Checking data type of InvoiceDate

In [ ]:
clean_df['InvoiceDate'].dtype

dtype('O')

Converting it to proper date time column from text

In [ ]:
pd.to_datetime(clean_df['InvoiceDate'])

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 524878, dtype: datetime64[ns]

Dropping exact duplicates

In [46]:
clean_df = clean_df.drop_duplicates()
print(clean_df.shape)

(536641, 8)

Removing invalid transactions

In [49]:
clean_df = clean_df[(clean_df['Quantity'] > 0) & (clean_df['UnitPrice'] > 0)]
print(clean_df.shape)

(524878, 8)

Creating a new sales column

In [50]:
clean_df['Sales'] = clean_df['Quantity'] * clean_df['UnitPrice']
print(clean_df.shape)

(524878, 9)